### PR TITLE
No convergence in MODFLOW doesn't result in an error anymore

### PR DESCRIPTION
**Pull request by Hofer-Julian**
See https://github.com/MODFLOW-USGS/modflow6/pull/1141 by @mjr-deltares 

@luitjansl You will probably want to merge this change into the lumbricus branch

### CODE REVIEW

**Review by luitjansl — APPROVED** [review]
looks good to me. If I understood correctly, Martijn will still need to update xmipy to make that   survive if mf6 does not converge. Has that already happened? You could consider waiting for that before removing this testcase. After all, this testcase documents the current expected behavior. Anyway, just a thought.

**Comment by Hofer-Julian** [comment]
> . If I understood correctly, Martijn will still need to update xmipy to make that survive if mf6 does not converge.

As far as I can tell, it already survives it now.
They way I've understood is that the change could happen in MODFLOW or xmipy, but MODFLOW is the better choice.
MODFLOW code has now been adapted.

**Comment by mjr-deltares** [comment]
> > . If I understood correctly, Martijn will still need to update xmipy to make that survive if mf6 does not converge.
> 
> As far as I can tell, it already survives it now. They way I've understood is that the change could happen in MODFLOW or xmipy, but MODFLOW is the better choice. MODFLOW code has now been adapted.

Yes, that is the intended behavior. If it doesn't work out this way, please let me know.

**Comment by Hofer-Julian** [comment]
@mjr-deltares The test was assuming that no convergence leads to a bmi error.
That assumption does not hold true anymore, so I would say your change works as expected :)

**Pull request merged**
